/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package a_yourstore.com;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    
}
